### ISSUE TITLE
Boot Strategy

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vds-elements#4]
## Tasks

- [x] Complete #8.
- [x] Build `BootStrategy` interface.
- [x] Connect to `Player` and test it.
- [x] Build and test `LazyBootStrategy`.
- [x] Build and test `ClickBootStrategy`.
- [x] Build and test `ImmediateBootStrategy`.

## References

- https://github.com/vidstack/player/blob/main/docs/architecture/architecture.md#boot-strategy

**Comment by mihar-22** [comment]
This has been removed whilst we plan out a better API.
