### ISSUE TITLE
Media Load Strategy

### ISSUE THREAD

**Issue by mihar-22** [vidstack/vds-elements#7]
## Tasks

- [x] Complete #8.
- [x] Complete #6.
- [x] Complete #4.
- [ ] Build `MediaLoadStrategy` interface.
- [ ] Connect to `Player` and test it.
- [ ] Build and test `FirstCanPlayMediaLoadStrategy`.

## References

- https://github.com/vidstack/player/blob/main/docs/architecture/architecture.md#media-load-strategy

**Comment by mihar-22** [comment]
Putting this in the backlog for now as it's thought through a little more. Going with a simple solution for now of using the first provider who can play the current source to load it immediately on change.
